# use the official python image from the docker hub
FROM python:3.9-slim

#set the working directory
WORKDIR /app

# copy the current directory content into the container at /app
COPY . /app

#Install any needed packages specified in requirements.txt
RUN pip install flask

EXPOSE 5000

CMD ["python","app.py"]